### ISSUE TITLE
[BUG] runtime.sigpanic while running F34 on aarch64

### ISSUE THREAD

**Issue by jbpratt** [redhat-et/microshift#219]
#### What happened:

Upon running `microshift`, I'm met with a large cgo trace, with what looks like an issue loading the boringssl DSO.

#### What you expected to happen:

A nice help command would be presented :smiley_cat: 

#### How to reproduce it (as minimally and precisely as possible):

1. Install FCOS34 on a Raspberry Pi (details below)
2. Once booted, follow the `install.sh` script (mainly install cri-{o,tools})
3. Download a build of microshift
4. execute it!

#### Anything else we need to know?:

Booting FCOS on an RPi4 can be done roughly like so:
1. Download RPi firemware
2. Download aarch64 FCOS image (https://builds.coreos.fedoraproject.org/browser?stream=testing-devel&arch=aarch64)
3. Create ignition file and generate image
```
podman run --pull=always \
	--privileged --rm \
	-v /dev:/dev \
	-v /run/udev:/run/udev \
	-v .:/data \
	-w /data quay.io/coreos/coreos-installer:release install ${DISK} -i ${IGN} -f ${IMAGE} --offline --insecure
```
4. Mount the second partition on the disk and unzip firmware
5. Boot! There is a 3GB memory limit that will need to be removed on restart.

#### Environment:
- Microshift version (use `microshift version`): https://github.com/redhat-et/microshift/releases/download/4.7.0-0.microshift-2021-08-10-163759/microshift-linux-arm64
- Hardware configuration: Raspberry Pi 4 (8GB)
- OS (e.g: `cat /etc/os-release`):

```
[core@kitkat ~]$ cat /etc/os-release
NAME=Fedora
VERSION="34.20210810.dev.0 (CoreOS)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora CoreOS 34.20210810.dev.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='34.20210810.dev.0'
DEFAULT_HOSTNAME=localhost
```

- Kernel (e.g. `uname -a`):
```
[core@kitkat ~]$ uname -a
Linux kitkat 5.13.7-200.fc34.aarch64 #1 SMP Sat Jul 31 13:54:43 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

#### Relevant Logs 
```
[core@kitkat ~]$ rpm-ostree status
State: idle
Deployments:
* fedora:fedora/aarch64/coreos/testing-devel
                   Version: 34.20210810.dev.0 (2021-08-10T01:22:06Z)
                BaseCommit: 6e1fb34b883d1f3b8ff413a5819978c2fa7721868606301826be44a3d6e2c83e
              GPGSignature: (unsigned)
           LayeredPackages: openssl-devel cri-tools cri-o

  fedora:fedora/aarch64/coreos/testing-devel
                   Version: 34.20210810.dev.0 (2021-08-10T01:22:06Z)
                BaseCommit: 6e1fb34b883d1f3b8ff413a5819978c2fa7721868606301826be44a3d6e2c83e
              GPGSignature: (unsigned)
           LayeredPackages: cri-tools cri-o
```

```
[core@kitkat ~]$ curl -LO https://github.com/redhat-et/microshift/releases/download/4.7.0-0.microshift-2021-08-10-163759/microshift-linux-arm64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   630  100   630    0     0   2985      0 --:--:-- --:--:-- --:--:--  2985
100  110M  100  110M    0     0   9.8M      0  0:00:11  0:00:11 --:--:-- 19.9M
[core@kitkat ~]$ sudo chmod +x microshift-linux-arm64
[core@kitkat ~]$ ./microshift-linux-arm64
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38288f70 pc=0xffff7e2ace94]

runtime stack:
runtime.throw(0x44322ce, 0x2a)
/usr/lib/golang/src/runtime/panic.go:1116 +0x54
runtime.sigpanic()
/usr/lib/golang/src/runtime/signal_unix.go:726 +0x444

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x38480e0, 0x400009ed38, 0x3e034c0)
/usr/lib/golang/src/runtime/cgocall.go:133 +0x50 fp=0x400009ed00 sp=0x400009ecc0 pc=0x403b40
crypto/internal/boring._Cfunc__goboringcrypto_DLOPEN_OPENSSL(0x0)
_cgo_gotypes.go:287 +0x44 fp=0x400009ed30 sp=0x400009ed00 pc=0x66e564
crypto/internal/boring.init.0()
/usr/lib/golang/src/crypto/internal/boring/boring.go:46 +0x40 fp=0x400009ed70 sp=0x400009ed30 pc=0x674400
runtime.doInit(0x6eb5a80)
/usr/lib/golang/src/runtime/proc.go:5652 +0x9c fp=0x400009edb0 sp=0x400009ed70 pc=0x442ffc
runtime.doInit(0x6eb1c80)
/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009edf0 sp=0x400009edb0 pc=0x442fb8
runtime.doInit(0x6edb280)
/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009ee30 sp=0x400009edf0 pc=0x442fb8
runtime.doInit(0x6edc680)
/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009ee70 sp=0x400009ee30 pc=0x442fb8
runtime.doInit(0x6e9ed20)
/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009eeb0 sp=0x400009ee70 pc=0x442fb8
runtime.doInit(0x6ed7720)
/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009eef0 sp=0x400009eeb0 pc=0x442fb8
runtime.doInit(0x6ed2d20)
/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009ef30 sp=0x400009eef0 pc=0x442fb8
runtime.doInit(0x6eae480)
/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009ef70 sp=0x400009ef30 pc=0x442fb8
runtime.main()
/usr/lib/golang/src/runtime/proc.go:191 +0x1b8 fp=0x400009efd0 sp=0x400009ef70 pc=0x435d08
runtime.goexit()
/usr/lib/golang/src/runtime/asm_arm64.s:1136 +0x4 fp=0x400009efd0 sp=0x400009efd0 pc=0x468904

goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x71cd1a0)
/opt/app-root/src/github.com/redhat-et/microshift/vendor/k8s.io/klog/v2/klog.go:1164 +0x70
created by k8s.io/klog/v2.init.0
/opt/app-root/src/github.com/redhat-et/microshift/vendor/k8s.io/klog/v2/klog.go:418 +0x124
```

looping in @dustymabe since we chatted about this

**Comment by rootfs** [comment]
@jbpratt thanks for test driving arm64, would you please get the entire back trace, especially `goroutine 19`?

**Comment by jbpratt** [comment]
Hi @rootfs! Sadly this is the entire trace that is shown. Here are 2 executions just now, though it doesn't seem very helpful. If there is a way to get more info out of this, please let me know. 

<details>
  <summary>Details</summary>

```
[core@kitkat ~]$ sudo ./microshift-linux-arm64
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1f6f9f70 pc=0xffff603a6e94]

runtime stack:
runtime.throw(0x44322ce, 0x2a)
	/usr/lib/golang/src/runtime/panic.go:1116 +0x54
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:726 +0x444

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x38480e0, 0x400009ad38, 0x3e034c0)
	/usr/lib/golang/src/runtime/cgocall.go:133 +0x50 fp=0x400009ad00 sp=0x400009acc0 pc=0x403b40
crypto/internal/boring._Cfunc__goboringcrypto_DLOPEN_OPENSSL(0x0)
	_cgo_gotypes.go:287 +0x44 fp=0x400009ad30 sp=0x400009ad00 pc=0x66e564
crypto/internal/boring.init.0()
	/usr/lib/golang/src/crypto/internal/boring/boring.go:46 +0x40 fp=0x400009ad70 sp=0x400009ad30 pc=0x674400
runtime.doInit(0x6eb5a80)
	/usr/lib/golang/src/runtime/proc.go:5652 +0x9c fp=0x400009adb0 sp=0x400009ad70 pc=0x442ffc
runtime.doInit(0x6eb1c80)
	/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009adf0 sp=0x400009adb0 pc=0x442fb8
runtime.doInit(0x6edb280)
	/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009ae30 sp=0x400009adf0 pc=0x442fb8
runtime.doInit(0x6edc680)
	/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009ae70 sp=0x400009ae30 pc=0x442fb8
runtime.doInit(0x6e9ed20)
	/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009aeb0 sp=0x400009ae70 pc=0x442fb8
runtime.doInit(0x6ed7720)
	/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009aef0 sp=0x400009aeb0 pc=0x442fb8
runtime.doInit(0x6ed2d20)
	/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009af30 sp=0x400009aef0 pc=0x442fb8
runtime.doInit(0x6eae480)
	/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009af70 sp=0x400009af30 pc=0x442fb8
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:191 +0x1b8 fp=0x400009afd0 sp=0x400009af70 pc=0x435d08
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_arm64.s:1136 +0x4 fp=0x400009afd0 sp=0x400009afd0 pc=0x468904

goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x71cd1a0)
	/opt/app-root/src/github.com/redhat-et/microshift/vendor/k8s.io/klog/v2/klog.go:1164 +0x70
created by k8s.io/klog/v2.init.0
	/opt/app-root/src/github.com/redhat-et/microshift/vendor/k8s.io/klog/v2/klog.go:418 +0x124
[core@kitkat ~]$ sudo ./microshift-linux-arm64
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3475cf70 pc=0xffff9103ce94]

runtime stack:
runtime.throw(0x44322ce, 0x2a)
	/usr/lib/golang/src/runtime/panic.go:1116 +0x54
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:726 +0x444

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x38480e0, 0x400009ad38, 0x3e034c0)
	/usr/lib/golang/src/runtime/cgocall.go:133 +0x50 fp=0x400009ad00 sp=0x400009acc0 pc=0x403b40
crypto/internal/boring._Cfunc__goboringcrypto_DLOPEN_OPENSSL(0x0)
	_cgo_gotypes.go:287 +0x44 fp=0x400009ad30 sp=0x400009ad00 pc=0x66e564
crypto/internal/boring.init.0()
	/usr/lib/golang/src/crypto/internal/boring/boring.go:46 +0x40 fp=0x400009ad70 sp=0x400009ad30 pc=0x674400
runtime.doInit(0x6eb5a80)
	/usr/lib/golang/src/runtime/proc.go:5652 +0x9c fp=0x400009adb0 sp=0x400009ad70 pc=0x442ffc
runtime.doInit(0x6eb1c80)
	/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009adf0 sp=0x400009adb0 pc=0x442fb8
runtime.doInit(0x6edb280)
	/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009ae30 sp=0x400009adf0 pc=0x442fb8
runtime.doInit(0x6edc680)
	/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009ae70 sp=0x400009ae30 pc=0x442fb8
runtime.doInit(0x6e9ed20)
	/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009aeb0 sp=0x400009ae70 pc=0x442fb8
runtime.doInit(0x6ed7720)
	/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009aef0 sp=0x400009aeb0 pc=0x442fb8
runtime.doInit(0x6ed2d20)
	/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009af30 sp=0x400009aef0 pc=0x442fb8
runtime.doInit(0x6eae480)
	/usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009af70 sp=0x400009af30 pc=0x442fb8
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:191 +0x1b8 fp=0x400009afd0 sp=0x400009af70 pc=0x435d08
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_arm64.s:1136 +0x4 fp=0x400009afd0 sp=0x400009afd0 pc=0x468904

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x71cd1a0)
	/opt/app-root/src/github.com/redhat-et/microshift/vendor/k8s.io/klog/v2/klog.go:1164 +0x70
created by k8s.io/klog/v2.init.0
	/opt/app-root/src/github.com/redhat-et/microshift/vendor/k8s.io/klog/v2/klog.go:418 +0x124
```

</details>

**Comment by rootfs** [comment]
@jbpratt this is interesting: `boring._Cfunc__goboringcrypto_DLOPEN_OPENSSL`, i think microshift is built without external library dependent, but can you run `ldd microshift-linux-arm64` to confirm? thanks

**Comment by jbpratt** [comment]
> @jbpratt this is interesting: `boring._Cfunc__goboringcrypto_DLOPEN_OPENSSL`, i think microshift is built without external library dependent, but can you run `ldd microshift-linux-arm64` to confirm? thanks

```
[core@kitkat ~]$ ldd microshift-linux-arm64
	not a dynamic executable
```

here you go!

**Comment by rootfs** [comment]
this is similar to [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1728223), the solution to the BZ is to drop the static build. cc @copejon

**Comment by jbpratt** [comment]
testing on Fedora Server 34 aarch64

````
[autumn@kitkat ~]$ uname -a
Linux kitkat 5.11.12-300.fc34.aarch64 #1 SMP Wed Apr 7 16:12:21 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

```
[autumn@kitkat ~]$ journalctl -u microshift.service
-- Journal begins at Mon 2021-04-05 19:00:00 CDT, ends at Sat 2021-09-18 08:57:54 CDT. --
Sep 18 08:54:22 kitkat systemd[1]: Started Microshift.
Sep 18 08:54:22 kitkat microshift[48269]: fatal error: unexpected signal during runtime execution
Sep 18 08:54:22 kitkat microshift[48269]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xc978f70 pc=0xffff59fdae94]
Sep 18 08:54:22 kitkat microshift[48269]: runtime stack:
Sep 18 08:54:22 kitkat microshift[48269]: runtime.throw(0x441668a, 0x2a)
Sep 18 08:54:22 kitkat microshift[48269]:         /usr/lib/golang/src/runtime/panic.go:1116 +0x54
Sep 18 08:54:22 kitkat microshift[48269]: runtime.sigpanic()
Sep 18 08:54:22 kitkat microshift[48269]:         /usr/lib/golang/src/runtime/signal_unix.go:726 +0x444
Sep 18 08:54:22 kitkat microshift[48269]: goroutine 1 [syscall, locked to thread]:
Sep 18 08:54:22 kitkat microshift[48269]: runtime.cgocall(0x3832b48, 0x400009bd38, 0x3dea100)
Sep 18 08:54:22 kitkat microshift[48269]:         /usr/lib/golang/src/runtime/cgocall.go:133 +0x50 fp=0x400009bd00 sp=0x400009bcc0 pc=0x403b40
Sep 18 08:54:22 kitkat microshift[48269]: crypto/internal/boring._Cfunc__goboringcrypto_DLOPEN_OPENSSL(0x0)
Sep 18 08:54:22 kitkat microshift[48269]:         _cgo_gotypes.go:287 +0x44 fp=0x400009bd30 sp=0x400009bd00 pc=0x66ea64
Sep 18 08:54:22 kitkat microshift[48269]: crypto/internal/boring.init.0()
Sep 18 08:54:22 kitkat microshift[48269]:         /usr/lib/golang/src/crypto/internal/boring/boring.go:46 +0x40 fp=0x400009bd70 sp=0x400009bd30 pc>
Sep 18 08:54:22 kitkat microshift[48269]: runtime.doInit(0x6e85600)
Sep 18 08:54:22 kitkat microshift[48269]:         /usr/lib/golang/src/runtime/proc.go:5652 +0x9c fp=0x400009bdb0 sp=0x400009bd70 pc=0x442ffc
Sep 18 08:54:22 kitkat microshift[48269]: runtime.doInit(0x6e81800)
Sep 18 08:54:22 kitkat microshift[48269]:         /usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009bdf0 sp=0x400009bdb0 pc=0x442fb8
Sep 18 08:54:22 kitkat microshift[48269]: runtime.doInit(0x6eaa540)
Sep 18 08:54:22 kitkat microshift[48269]:         /usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009be30 sp=0x400009bdf0 pc=0x442fb8
Sep 18 08:54:22 kitkat microshift[48269]: runtime.doInit(0x6eaba80)
Sep 18 08:54:22 kitkat microshift[48269]:         /usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009be70 sp=0x400009be30 pc=0x442fb8
Sep 18 08:54:22 kitkat microshift[48269]: runtime.doInit(0x6e6e8a0)
Sep 18 08:54:22 kitkat microshift[48269]:         /usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009beb0 sp=0x400009be70 pc=0x442fb8
Sep 18 08:54:22 kitkat microshift[48269]: runtime.doInit(0x6ea6d80)
Sep 18 08:54:22 kitkat microshift[48269]:         /usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009bef0 sp=0x400009beb0 pc=0x442fb8
Sep 18 08:54:22 kitkat microshift[48269]: runtime.doInit(0x6ea2580)
Sep 18 08:54:22 kitkat microshift[48269]:         /usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009bf30 sp=0x400009bef0 pc=0x442fb8
Sep 18 08:54:22 kitkat microshift[48269]: runtime.doInit(0x6e7e000)
Sep 18 08:54:22 kitkat microshift[48269]:         /usr/lib/golang/src/runtime/proc.go:5647 +0x58 fp=0x400009bf70 sp=0x400009bf30 pc=0x442fb8
Sep 18 08:54:22 kitkat microshift[48269]: runtime.main()
Sep 18 08:54:22 kitkat microshift[48269]:         /usr/lib/golang/src/runtime/proc.go:191 +0x1b8 fp=0x400009bfd0 sp=0x400009bf70 pc=0x435d08
Sep 18 08:54:22 kitkat microshift[48269]: runtime.goexit()
Sep 18 08:54:22 kitkat microshift[48269]:         /usr/lib/golang/src/runtime/asm_arm64.s:1136 +0x4 fp=0x400009bfd0 sp=0x400009bfd0 pc=0x468904
Sep 18 08:54:22 kitkat microshift[48269]: goroutine 6 [chan receive]:
Sep 18 08:54:22 kitkat microshift[48269]: k8s.io/klog/v2.(*loggingT).flushDaemon(0x712f740)
Sep 18 08:54:22 kitkat microshift[48269]:         /opt/app-root/src/github.com/redhat-et/microshift/vendor/k8s.io/klog/v2/klog.go:1164 +0x70
Sep 18 08:54:22 kitkat microshift[48269]: created by k8s.io/klog/v2.init.0
Sep 18 08:54:22 kitkat microshift[48269]:         /opt/app-root/src/github.com/redhat-et/microshift/vendor/k8s.io/klog/v2/klog.go:418 +0x124
Sep 18 08:54:22 kitkat systemd[1]: microshift.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 18 08:54:22 kitkat systemd[1]: microshift.service: Failed with result 'exit-code'.
Sep 18 08:54:22 kitkat systemd[1]: microshift.service: Scheduled restart job, restart counter is at 1.
Sep 18 08:54:22 kitkat systemd[1]: Stopped Microshift.
Sep 18 08:54:22 kitkat systemd[1]: Started Microshift.
Sep 18 08:54:22 kitkat microshift[48280]: fatal error: unexpected signal during runtime execution
Sep 18 08:54:22 kitkat microshift[48280]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x32314f70 pc=0xffff91f05e94]
Sep 18 08:54:22 kitkat microshift[48280]: runtime stack:
Sep 18 08:54:22 kitkat microshift[48280]: runtime.throw(0x441668a, 0x2a)
Sep 18 08:54:22 kitkat microshift[48280]:         /usr/lib/golang/src/runtime/panic.go:1116 +0x54
Sep 18 08:54:22 kitkat microshift[48280]: runtime.sigpanic()
Sep 18 08:54:22 kitkat microshift[48280]:         /usr/lib/golang/src/runtime/signal_unix.go:726 +0x444
Sep 18 08:54:22 kitkat microshift[48280]: goroutine 1 [syscall, locked to thread]:
Sep 18 08:54:22 kitkat microshift[48280]: runtime.cgocall(0x3832b48, 0x400009bd38, 0x3dea100)
Sep 18 08:54:22 kitkat microshift[48280]:         /usr/lib/golang/src/runtime/cgocall.go:133 +0x50 fp=0x400009bd00 sp=0x400009bcc0 pc=0x403b40
Sep 18 08:54:22 kitkat microshift[48280]: crypto/internal/boring._Cfunc__goboringcrypto_DLOPEN_OPENSSL(0x0)
Sep 18 08:54:22 kitkat microshift[48280]:         _cgo_gotypes.go:287 +0x44 fp=0x400009bd30 sp=0x400009bd00 pc=0x66ea64
Sep 18 08:54:22 kitkat microshift[48280]: crypto/internal/boring.init.0()
Sep 18 08:54:22 kitkat microshift[48280]:         /usr/lib/golang/src/crypto/internal/boring/boring.go:46 +0x40 fp=0x400009bd70 sp=0x400009bd30 pc>
```
